language: python
branches:
  only:
  - master
matrix:
  include:
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
install: pip install -e .[TEST]
script: pytest tests --cov=labelbot --cov-branch
notifications:
  email: false
after_success:
- codecov
