language: python
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"
matrix:
  include:
  - os: linux
    python: 3.7
    dist: xenial
    sudo: true
install: pip install -e .[TEST]
script: pytest tests --cov=labelbot --cov-branch
notifications:
  email: false
after_success:
- codecov
- "./package.sh"
deploy:
  on:
    tags: true
  provider: lambda
  function_name: awsdeploy
  region: eu-west-2
  role: arn:aws:iam::362041922967:role/service-role/awsdeploy-role-bhr31bsw
  runtime: python3.7
  module_name: labelbot.bot
  handler_name: lambda_handler
  zip: labelbot.zip
  secret_access_key:
    secure: gv/qbN7Lc/DSZivg6z8mNiCRr1w+FE2G2WIYP+ayid9PGGIkiK9WqqCx2FSGCxmAL5EtUXR8nrPDMzhl91Ba+Zhj/Ew2AJOBy5ZYuN2WVtK6nOocGTGEtaSFa8d/kdrQijMwHxZTF4fnKcL4koEGclN+bk6dVLejFZkpZlnpG/AYqSW5TiGjhml1J1nuGFk1Tdvqfpenv8D4lzNKRAfg1ulGFvYcOCLELJ2mhdoy7jUvUdLbgTrKQ8hkJjOPDtqzcXhQY9x9MTKKlejodC76HLQI+WE33mFzDytYVAwVwlLCxEM69b095bOXEOj6kV1b/myJwmnHqlM0i1jsXTbiDBOp0zrckKbFOYh2NFfSLYFdpEOW7eTX6doM+aZzIVqZ1B8+T+DP6Nq/FhuMJWBar0APt5PIhPFZSceAdj7622ag9YZuQk2I2/1Q3oa4gLdIMxhl5n2u2OLE2PIP56DGThXYgK2R1OrXPnv6V5/jj0J0GmbTHOxiyUz4D/lLoi0kw5SPN1rN7HpxyVMzwsgaEhkm7vL+i8DvGYKz/jyKKSDC0yvqYsZT/o2L+xpbtOUSlDLtvf4I/fxI3BOojjXq5dFMpdy8tFc9d+36zVHub9glgWJnsspMub9RwBusLsdfg/NaZFnrjHukWtAL0VsKnDCxSJ0Bwp6wmgyO7Z0bm7A=
  access_key_id:
    secure: cxQRUfwMak76MVy3MVzh/D7XI5Vrh+FeaTIlOANEoSdw52kk6NCGvrx/Lx537o4nPdRGYhL90BLYgimbmUODD0TnwDBKjOnp7/m3B+tJ7zflRdAyKmBx3nd0iVi6Em1Nm75NT6NcEdF930r93dA/u4KlorMvblI3lFFxJf5GmENXD+PlXwRTcLRGuLABF2YcRaACMjy6Yi2ASEIWr9ook+zEEvmdJdXjCxniCYSMDq0UobUQdgTKMzM4DZdDnLJoNXZC+RYWpKtpibF2XsCnR7myP9nknmstaoH6yD29769GCDh5h8b0002DMoEXR/esV+QNqsdKy1iCdqvkurTF0TlalEORx6pd1gznFY+cbyr/LxX2YAYBNQnqvHuolv4IL1PXhaWKoRCn1wT3aDhD3zhg3gmN7yLCdD1rLHOnt2nYMl1pNL3KC34Tzh0rFHyari5C26T72st1+f3NFhgY2F7IWg2U+xxtK4RCrqkdZiShF/jZgtHuLYqlNsalA/0VUL3XNOWftkvVFjQm9LokPurPOUB2HAMDxiyhbmWfRM3665juPWYV5zPbuBIJnIgHzNh86MFaE7Q9RZwD8VJwQxYrm094AK9cOnNigAMnswuF9FJm7w7zzkgyYaG71enq6hPAsli86yDV4DGJhO+HzVVE7Pv3tlMoie9YKSQGFt0=
